library(ggplot2)
library(lubridate)
library(ggmap)
library(xgboost)
library(randomForest)
library(Matrix)
train <- read.csv("train.csv", header = TRUE, stringsAsFactors = FALSE)
test  <- read.csv("test.csv", header = TRUE, stringsAsFactors = FALSE)
sample <- read.csv("sampleSubmission.csv", header = T, stringsAsFactors = FALSE)
map <- get_map(location="sanfrancisco",zoom=12,source="osm", color = 'bw')